"""Schema initializer from deployed commit 000dea6, for migration regression tests only."""
def _migrar_envelopes_legados():
    """Converte envelopes antigos em orçamento mensal por categoria.

    A versão 2.0 não usa orçamento como lançamento. As colunas legadas continuam
    no schema apenas para restaurar backups antigos, mas ficam inativas depois
    desta migração.
    """
    with transaction() as cur:
        cur.execute("\n            INSERT INTO orcamentos_categorias\n                (competencia, categoria, subgrupo, valor_planejado, origem)\n            SELECT DATE_TRUNC('month', l.data_vencimento)::date,\n                   l.categoria, NULLIF(BTRIM(COALESCE(l.subgrupo,'')), ''),\n                   MAX(COALESCE(l.valor_orcamento, l.valor, 0)), 'migrado_envelope'\n            FROM lancamentos l\n            WHERE COALESCE(l.eh_orcamento,0)=1\n            GROUP BY DATE_TRUNC('month', l.data_vencimento)::date,\n                     l.categoria, NULLIF(BTRIM(COALESCE(l.subgrupo,'')), '')\n            ON CONFLICT DO NOTHING\n        ")
        cur.execute("\n            INSERT INTO orcamentos_categorias\n                (competencia, categoria, subgrupo, valor_planejado, origem)\n            SELECT DATE_TRUNC('month', CURRENT_DATE)::date, c.categoria,\n                   NULLIF(BTRIM(COALESCE(c.subgrupo,'')), ''),\n                   COALESCE(c.valor_padrao,0), 'migrado_categoria'\n            FROM categorias_personalizadas c\n            WHERE COALESCE(c.is_envelope,0)=1 AND COALESCE(c.valor_padrao,0) > 0\n            ON CONFLICT DO NOTHING\n        ")
        cur.execute('\n            DELETE FROM recorrencias_geradas rg\n            USING categorias_personalizadas c\n            WHERE rg.categoria_id=c.id AND COALESCE(c.is_envelope,0)=1\n        ')
        cur.execute('DELETE FROM lancamentos WHERE COALESCE(eh_orcamento,0)=1')
        cur.execute('\n            UPDATE categorias_personalizadas\n            SET is_envelope=0, is_recorrente=0\n            WHERE COALESCE(is_envelope,0)=1\n        ')

def init_db():
    """Migrações compatíveis com a base existente, sem exigir reset manual."""
    execute_query('\n        CREATE TABLE IF NOT EXISTS categorias_personalizadas (\n            id SERIAL PRIMARY KEY,\n            tipo TEXT,\n            categoria TEXT,\n            subgrupo TEXT,\n            valor_padrao NUMERIC,\n            atraso_meses INTEGER,\n            dia_pagamento INTEGER,\n            is_recorrente INTEGER DEFAULT 0,\n            data_inicio DATE,\n            is_envelope INTEGER DEFAULT 0\n        );\n    ')
    for ddl in ['ALTER TABLE categorias_personalizadas ADD COLUMN IF NOT EXISTS valor_padrao NUMERIC;', 'ALTER TABLE categorias_personalizadas ADD COLUMN IF NOT EXISTS atraso_meses INTEGER;', 'ALTER TABLE categorias_personalizadas ADD COLUMN IF NOT EXISTS dia_pagamento INTEGER;', 'ALTER TABLE categorias_personalizadas ADD COLUMN IF NOT EXISTS is_recorrente INTEGER DEFAULT 0;', 'ALTER TABLE categorias_personalizadas ADD COLUMN IF NOT EXISTS data_inicio DATE;', 'ALTER TABLE categorias_personalizadas ADD COLUMN IF NOT EXISTS is_envelope INTEGER DEFAULT 0;', 'ALTER TABLE categorias_personalizadas ADD COLUMN IF NOT EXISTS is_producao_variavel INTEGER DEFAULT 0;', 'ALTER TABLE categorias_personalizadas ADD COLUMN IF NOT EXISTS modalidade_renda TEXT;']:
        execute_query(ddl)
    execute_query("\n        UPDATE categorias_personalizadas\n        SET is_producao_variavel=1\n        WHERE tipo='Entrada'\n          AND (TRIM(COALESCE(modalidade_renda,''))='Plantões'\n               OR LOWER(TRIM(COALESCE(categoria,''))) LIKE 'plant%')\n    ")
    execute_query("\n        UPDATE categorias_personalizadas\n        SET modalidade_renda='Variável'\n        WHERE tipo='Entrada' AND TRIM(COALESCE(modalidade_renda,''))='Plantões'\n    ")
    execute_query("\n        CREATE TABLE IF NOT EXISTS orcamentos_categorias (\n            id BIGSERIAL PRIMARY KEY,\n            competencia DATE NOT NULL,\n            categoria TEXT NOT NULL,\n            subgrupo TEXT,\n            valor_planejado NUMERIC NOT NULL DEFAULT 0 CHECK (valor_planejado >= 0),\n            origem TEXT NOT NULL DEFAULT 'manual',\n            criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n            atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()\n        );\n    ")
    execute_query("\n        CREATE UNIQUE INDEX IF NOT EXISTS ux_orcamento_categoria_mes\n        ON orcamentos_categorias (competencia, categoria, COALESCE(subgrupo,''));\n    ")
    execute_query("\n        CREATE TABLE IF NOT EXISTS lancamentos (\n            id SERIAL PRIMARY KEY,\n            tipo TEXT,\n            categoria TEXT,\n            subgrupo TEXT,\n            descricao TEXT,\n            valor NUMERIC,\n            data_vencimento DATE,\n            parcela_atual INTEGER,\n            total_parcelas INTEGER,\n            pago INTEGER DEFAULT 0,\n            compra_id TEXT,\n            forma_pagamento TEXT DEFAULT 'Outros',\n            prioridade TEXT DEFAULT 'Baixa 🟢',\n            valor_pago NUMERIC DEFAULT 0.0\n        );\n    ")
    for ddl in ["ALTER TABLE lancamentos ADD COLUMN IF NOT EXISTS forma_pagamento TEXT DEFAULT 'Outros';", "ALTER TABLE lancamentos ADD COLUMN IF NOT EXISTS prioridade TEXT DEFAULT 'Baixa 🟢';", 'ALTER TABLE lancamentos ADD COLUMN IF NOT EXISTS valor_pago NUMERIC DEFAULT 0.0;', 'ALTER TABLE lancamentos ADD COLUMN IF NOT EXISTS eh_estimativa INTEGER DEFAULT 0;', 'ALTER TABLE lancamentos ADD COLUMN IF NOT EXISTS data_competencia DATE;', 'ALTER TABLE lancamentos ADD COLUMN IF NOT EXISTS data_pagamento DATE;', 'ALTER TABLE lancamentos ADD COLUMN IF NOT EXISTS eh_orcamento INTEGER DEFAULT 0;', 'ALTER TABLE lancamentos ADD COLUMN IF NOT EXISTS valor_orcamento NUMERIC;']:
        execute_query(ddl)
    execute_query('UPDATE lancamentos SET data_competencia = data_vencimento WHERE data_competencia IS NULL')
    execute_query("\n        UPDATE lancamentos\n        SET data_competencia = TO_DATE(SUBSTRING(descricao FROM '\\(([0-9]{2}/[0-9]{2}/[0-9]{4})\\)'), 'DD/MM/YYYY')\n        WHERE tipo = 'Entrada' AND descricao LIKE 'Plantão %'\n          AND descricao ~ '\\([0-9]{2}/[0-9]{2}/[0-9]{4}\\)'\n    ")
    execute_query('UPDATE lancamentos SET data_pagamento = data_vencimento WHERE pago = 1 AND data_pagamento IS NULL')
    execute_query('\n        CREATE TABLE IF NOT EXISTS info_dividas (\n            compra_id TEXT PRIMARY KEY,\n            credor TEXT,\n            taxa_juros_mensal NUMERIC\n        );\n    ')
    execute_query('\n        CREATE TABLE IF NOT EXISTS reserva_emergencia (\n            id INTEGER PRIMARY KEY DEFAULT 1,\n            valor NUMERIC DEFAULT 0,\n            atualizado_em DATE\n        );\n    ')
    execute_query('INSERT INTO reserva_emergencia (id, valor, atualizado_em) VALUES (1, 0, CURRENT_DATE) ON CONFLICT (id) DO NOTHING;')
    execute_query("\n        CREATE TABLE IF NOT EXISTS pagamentos (\n            id BIGSERIAL PRIMARY KEY,\n            lancamento_id INTEGER NOT NULL REFERENCES lancamentos(id) ON DELETE CASCADE,\n            valor NUMERIC NOT NULL,\n            data_pagamento DATE NOT NULL,\n            origem TEXT NOT NULL DEFAULT 'sincronizado',\n            criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n            UNIQUE (lancamento_id, origem)\n        );\n    ")
    execute_query('\n        CREATE OR REPLACE FUNCTION fn_normalizar_pagamento_lancamento()\n        RETURNS trigger AS $$\n        BEGIN\n            IF NEW.pago = 1 THEN\n                IF COALESCE(NEW.valor_pago, 0) = 0 THEN\n                    NEW.valor_pago := NEW.valor;\n                END IF;\n                IF NEW.data_pagamento IS NULL THEN\n                    NEW.data_pagamento := CURRENT_DATE;\n                END IF;\n            ELSE\n                NEW.valor_pago := 0;\n                NEW.data_pagamento := NULL;\n            END IF;\n            RETURN NEW;\n        END;\n        $$ LANGUAGE plpgsql;\n    ')
    execute_query('DROP TRIGGER IF EXISTS trg_normalizar_pagamento_lancamento ON lancamentos;')
    execute_query('\n        CREATE TRIGGER trg_normalizar_pagamento_lancamento\n        BEFORE INSERT OR UPDATE OF pago, valor_pago, data_pagamento\n        ON lancamentos\n        FOR EACH ROW EXECUTE FUNCTION fn_normalizar_pagamento_lancamento();\n    ')
    execute_query("\n        CREATE OR REPLACE FUNCTION fn_sincronizar_pagamento_lancamento()\n        RETURNS trigger AS $$\n        BEGIN\n            IF NEW.pago = 1 AND COALESCE(NEW.valor_pago, 0) > 0 THEN\n                INSERT INTO pagamentos (lancamento_id, valor, data_pagamento, origem)\n                VALUES (NEW.id, NEW.valor_pago, COALESCE(NEW.data_pagamento, CURRENT_DATE), 'sincronizado')\n                ON CONFLICT (lancamento_id, origem)\n                DO UPDATE SET valor = EXCLUDED.valor, data_pagamento = EXCLUDED.data_pagamento;\n            ELSE\n                DELETE FROM pagamentos WHERE lancamento_id = NEW.id AND origem = 'sincronizado';\n            END IF;\n            RETURN NEW;\n        END;\n        $$ LANGUAGE plpgsql;\n    ")
    execute_query('DROP TRIGGER IF EXISTS trg_sincronizar_pagamento_lancamento ON lancamentos;')
    execute_query('\n        CREATE TRIGGER trg_sincronizar_pagamento_lancamento\n        AFTER INSERT OR UPDATE OF pago, valor_pago, data_pagamento\n        ON lancamentos\n        FOR EACH ROW EXECUTE FUNCTION fn_sincronizar_pagamento_lancamento();\n    ')
    execute_query("\n        INSERT INTO pagamentos (lancamento_id, valor, data_pagamento, origem)\n        SELECT id, valor_pago, COALESCE(data_pagamento, data_vencimento), 'sincronizado'\n        FROM lancamentos\n        WHERE pago = 1 AND COALESCE(valor_pago, 0) > 0\n        ON CONFLICT (lancamento_id, origem)\n        DO UPDATE SET valor = EXCLUDED.valor, data_pagamento = EXCLUDED.data_pagamento;\n    ")
    execute_query('\n        CREATE TABLE IF NOT EXISTS recorrencias_geradas (\n            categoria_id INTEGER NOT NULL REFERENCES categorias_personalizadas(id) ON DELETE CASCADE,\n            competencia DATE NOT NULL,\n            criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n            PRIMARY KEY (categoria_id, competencia)\n        );\n    ')
    execute_query("\n        INSERT INTO recorrencias_geradas (categoria_id, competencia)\n        SELECT CAST(SUBSTRING(l.compra_id FROM 5) AS INTEGER), DATE_TRUNC('month', l.data_vencimento)::date\n        FROM lancamentos l\n        JOIN categorias_personalizadas c\n          ON l.compra_id = ('rec_' || c.id::text)\n        WHERE l.compra_id ~ '^rec_[0-9]+$'\n        ON CONFLICT DO NOTHING;\n    ")
    execute_query('\n        CREATE TABLE IF NOT EXISTS preferencias_app (\n            chave TEXT PRIMARY KEY,\n            valor TEXT,\n            atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()\n        );\n    ')
    _migrar_envelopes_legados()
    execute_query('\n        CREATE OR REPLACE VIEW vw_lancamentos_financeiros AS\n        SELECT\n            l.id, l.tipo, l.categoria, l.subgrupo, l.descricao, l.valor,\n            l.data_vencimento, l.parcela_atual, l.total_parcelas, l.pago,\n            l.compra_id, l.forma_pagamento, l.prioridade, l.valor_pago,\n            l.eh_estimativa, l.data_competencia, l.data_pagamento,\n            l.eh_orcamento, l.valor_orcamento\n        FROM lancamentos l;\n    ')
    constraints = {'ck_lanc_tipo': "tipo IN ('Entrada','Despesa')", 'ck_lanc_pago': 'pago IN (0,1)', 'ck_lanc_valor': 'valor >= 0', 'ck_lanc_valor_pago': 'valor_pago >= 0', 'ck_lanc_parcela_atual': 'parcela_atual IS NULL OR parcela_atual >= 1', 'ck_lanc_total_parcelas': 'total_parcelas IS NULL OR total_parcelas >= 1', 'ck_lanc_parcelas_ordem': 'parcela_atual IS NULL OR total_parcelas IS NULL OR total_parcelas = 999 OR parcela_atual <= total_parcelas'}
    for nome, regra in constraints.items():
        execute_query(f"DO $$ BEGIN\n            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = '{nome}') THEN\n                ALTER TABLE lancamentos ADD CONSTRAINT {nome} CHECK ({regra}) NOT VALID;\n            END IF;\n        END $$;")
    execute_query("DO $$ BEGIN\n        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_cat_tipo') THEN\n            ALTER TABLE categorias_personalizadas\n            ADD CONSTRAINT ck_cat_tipo CHECK (tipo IN ('Entrada','Despesa')) NOT VALID;\n        END IF;\n    END $$;")
    for ddl in ['CREATE INDEX IF NOT EXISTS idx_lanc_data_vencimento ON lancamentos(data_vencimento);', 'CREATE INDEX IF NOT EXISTS idx_lanc_data_pagamento ON lancamentos(data_pagamento);', 'CREATE INDEX IF NOT EXISTS idx_lanc_data_competencia ON lancamentos(data_competencia);', 'CREATE INDEX IF NOT EXISTS idx_lanc_compra_id ON lancamentos(compra_id);', 'CREATE INDEX IF NOT EXISTS idx_lanc_pago_data ON lancamentos(pago, data_vencimento);', 'CREATE INDEX IF NOT EXISTS idx_lanc_tipo_data ON lancamentos(tipo, data_vencimento);', 'CREATE INDEX IF NOT EXISTS idx_lanc_categoria_subgrupo_data ON lancamentos(categoria, subgrupo, data_vencimento, pago);', 'CREATE INDEX IF NOT EXISTS idx_cat_tipo_categoria_subgrupo ON categorias_personalizadas(tipo, categoria, subgrupo);']:
        execute_query(ddl)
    execute_query("DO $$ BEGIN\n        IF NOT EXISTS (\n            SELECT 1 FROM categorias_personalizadas\n            GROUP BY tipo, categoria, COALESCE(subgrupo,'') HAVING COUNT(*) > 1\n        ) AND NOT EXISTS (\n            SELECT 1 FROM pg_indexes WHERE indexname = 'uq_cat_logica'\n        ) THEN\n            CREATE UNIQUE INDEX uq_cat_logica\n            ON categorias_personalizadas(tipo, categoria, (COALESCE(subgrupo,'')));\n        END IF;\n    END $$;")
